TRUNCATE TABLE question;
INSERT INTO question (question_text, answer, score) VALUES
                                                        ('저장소를 초기화하는 명령어: git __', 'init', 5),
                                                        ('파일을 스테이징 영역에 추가하는 명령어: git ___ <file>', 'add', 5),
                                                        ('모든 변경 파일을 스테이징하는 명령어: git add ___', '.', 5),
                                                        ('커밋 메시지를 포함하여 커밋하는 명령어: git commit ___ "message"', '-m', 5),
                                                        ('새 브랜치를 생성하는 명령어: git ___ <branch>', 'branch', 5),
                                                        ('현재 브랜치에서 다른 브랜치를 현재 브랜치로 병합하는 명령어: git ___ <branch>', 'merge', 5),
                                                        ('브랜치를 삭제하는 명령어: git branch ___ <branch>', '-d', 5),
                                                        ('현재 브랜치 이름을 출력하는 옵션: git branch --show- ___', 'current', 5),
                                                        ('브랜치 이동 명령어: git ___ <branch>', 'switch', 5),
                                                        ('스테이징된 파일과 마지막 커밋의 차이를 보여주는 명령어: git diff ___', '--staged', 5),
                                                        ('Git이 추적하지 않는 파일을 강제로 삭제하는 명령어: git ___ ___', 'clean -f', 10),
                                                        ('브랜치 이름을 변경하는 명령어: git ___ ___ <old> <new>', 'branch -m', 10),
                                                        ('브랜치를 생성하면서 바로 이동하는 명령어: git ___ ___ <branch>', 'switch -c', 10),
                                                        ('현재 작업 디렉토리의 상태를 확인하는 명령어:', 'git status', 10),
                                                        ('워킹 디렉토리의 변경 내용을 확인하는 명령어:', 'git diff', 10),
                                                        ('원격 저장소에서 특정 브랜치만 가져오려면 다음 중 빈칸에 들어갈 단어는? git fetch origin ____', 'main', 5),
                                                        ('현재 연결된 원격 저장소 목록과 URL을 확인하는 명령어 옵션은? git remote ___', '-v', 5),
                                                        ('원격 저장소에서 최신 커밋을 가져오되 로컬 브랜치를 수정하지 않는 명령어는? git ______', 'fetch', 5),
                                                        ('원격 저장소의 최신 내용을 가져오고 자동으로 병합까지 수행하는 명령어는? git ____', 'pull', 5),
                                                        ('로컬 변경 사항을 원격 저장소 main 브랜치로 업로드하는 명령어는? git ____ origin main', 'push', 5),
                                                        ('커밋하지 않은 변경 사항을 임시로 저장하는 명령어는? git ______', 'stash', 10),
                                                        ('등록된 원격 저장소 origin 을 삭제하는 명령어는? git remote ______ origin', 'remove', 5),
                                                        ('원격 브랜치를 삭제할 때 사용하는 명령어는? git push origin --______ <브랜치명>', 'delete', 5),
                                                        ('원격 저장소의 상세 정보(추적 브랜치 등)를 확인하는 명령어는? git remote ____ origin', 'show', 5),
                                                        ('원격 저장소 URL을 변경하기 위한 명령어: git remote set-___ ____ <새 URL>', 'url origin', 5),
                                                        ('원격 저장소를 추가하는 명령어: git ______ ______ <URL>', 'remote add', 10),
                                                        ('원격 저장소의 별칭 목록을 확인하는 명령어는 git ______이다.', 'remote', 10),
                                                        ('원격 저장소와 연결되어 있는 브랜치를 확인하려면 git ______ ______ 명령어를 사용한다.', 'branch -r', 10),
                                                        ('특정 커밋의 변경 사항을 되돌리는 새로운 커밋을 생성하는 명령어: git ______ <commit_hash>', 'revert', 10),
                                                        ('스테이징된 파일을 스테이징에서 제거하는 명령어: git reset ___ <file>', 'HEAD', 5),
                                                        ('마지막 커밋 메시지를 수정하는 명령어: git commit ___', '--amend', 5),
                                                        ('커밋 로그를 한줄 형식으로 출력하려면 git log ___ 옵션을 사용한다.', '--oneline', 5),
                                                        ('스테이징된 모든 파일을 unstage하는 명령어: git ___ ___', 'reset HEAD', 5),
                                                        ('특정 커밋으로 워킹 디렉토리를 되돌리는 명령어: git ___ <커밋해시>', 'checkout', 5),
                                                        ('마지막 커밋을 취소하되 변경사항은 유지하려면 git reset ___ HEAD~1', '--soft', 10),
                                                        ('마지막 커밋을 취소하고 변경사항도 버리려면 git reset ___ HEAD~1', '--hard', 10),
                                                        ('Git이 특정 파일을 추적하지 않도록 제외하려면 ___ 파일에 규칙을 추가한다.', '.gitignore', 10),
                                                        ('특정 파일을 변경 전 상태로 되돌리려면 git restore ___ <파일명>', '--staged', 10),
                                                        ('특정 파일을 직전 커밋 상태로 되돌리려면 git restore ___ <파일명>', '--source', 10);